name: 'makepad-packaging-action'
description: 'Build And Release Makepad Apps, including MacOS, Windows, Linux, Android and iOS, using GitHub Actions.'
author: 'Tyrese Luo <tyreseluo@outlook.com>'
branding:
  icon: 'box'
  color: 'blue'

inputs:
  args:
    description: 'Arguments for the `cargo build <args>` and `cargo makepad <args>` commands. For example, `--release --target x86_64-pc-windows-msvc`.'


  packager_formats:
    description: 'Comma-separated formats for `cargo packager` (e.g., deb,dmg,nsis).'

  packager_args:
    description: 'Extra arguments passed only to `cargo packager` (e.g., `--verbose`).'

  tagName:
    description: 'GitHub Release tag name. Supports `__VERSION__` placeholder.'

  releaseName:
    description: 'GitHub Release name. Supports `__VERSION__` placeholder.'

  releaseBody:
    description: 'GitHub Release body markdown.'

  releaseId:
    description: 'Existing GitHub Release ID. When provided, assets are uploaded to this release and no new release is created.'

  upload_updater_json:
    description: 'Whether to upload a static JSON file for the updater using GitHub Releases as the CDN'
    default: 'true'

  asset_name_template:
    description: 'Template for release asset names. Supports __APP__, __VERSION__, __PLATFORM__, __ARCH__, __MODE__, __EXT__, __FILENAME__, __BASENAME__.'

  asset_prefix:
    description: 'Optional prefix prepended to generated asset names.'

  releaseDraft:
    description: 'Create the release as a draft.'
    default: 'false'

  prerelease:
    description: 'Mark the release as a prerelease.'
    default: 'false'

  github_token:
    description: 'GitHub token for creating releases and uploading assets. Defaults to env GITHUB_TOKEN.'

  app_name:
    description: 'The name of the makepad app. If not provided, Mobile will be inferred from `Cargo.toml` name field, Desktop will be inferred from `cargo-packager` product_name field.'

  app_version:
    description: 'The version of the makepad app. If not provided, it will be inferred from `Cargo.toml` version field.'

  identifier:
    description: 'The bundle identifier for the app (e.g., com.example.makepadapp).'

  project_path:
    description: 'The path to the Makepad project. Defaults to the root of the repository.'
    default: '.'

  include_release:
    description: 'Whether to include the release build (default: true)'
    default: 'true'

  include_debug:
    description: 'Whether to include the debug build (default: false)'
    default: 'false'

outputs:
  artifacts:
    description: 'JSON array of artifacts built by the action.'
  app_name:
    description: 'Resolved app name.'
  app_version:
    description: 'Resolved app version.'
  release_url:
    description: 'GitHub Release URL (if created).'

runs:
  using: node24
  main: 'dist/index.js'
